name: Task Manager CI/CD Pipeline

on:
  push:
    branches: main
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build images
        run: docker compose --profile test build

      - name: Start MongoDB
        run: docker compose up -d mongodb

      - name: Wait for MongoDB
        run: |
          until docker inspect --format='{{.State.Health.Status}}' mongo-db | grep healthy; do
            echo "Waiting for MongoDB..."
            sleep 3
          done

      - name: Run unit tests
        run: docker compose run test

      - name: Copy coverage from container
        run: |
          CONTAINER_ID=$(docker ps -aqf "name=task_tests")
          docker cp $CONTAINER_ID:/app/htmlcov ./coverage

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/

      - name: Docker cleanup
        if: always()
        run: docker compose down -v
