name: Task Manager CI/CD Pipeline

on:
  push:
    branches: main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-test:
    name: Build & Unit Test
    runs-on: ubuntu-latest

    steps:    
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Build images
        run: docker compose --profile test build

      - name: Start MongoDB
        run: docker compose up -d mongodb
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


      - name: Wait for MongoDB
        run: |
          until docker inspect --format='{{.State.Health.Status}}' mongo-db | grep healthy; do
            echo "Waiting for MongoDB..."
            sleep 3
          done
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


      - name: Run unit tests
        run: docker compose run --rm test
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


      - name: Docker cleanup
        if: always()
        run: docker compose down -v
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        
  package-and-integration-tests:
    name: Package & Integration Tests
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build task manager app
        run: docker build -t task-manager:latest .
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


      - name: Save Docker image
        run: docker save task-manager:latest | gzip > task-manager-image.tar.gz

      - name: Upload Docker image
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: task-manager-image.tar.gz
          retention-days: 1

      - name: Build application + database - mongo
        run: docker compose build
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

        
      - name: Start E2E environment
        run: docker compose up -d
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


      - name: Run E2E tests
        run: |
          echo "Waiting for API to be ready..."
        
          for i in {1..4}; do
            echo "Attempt $i/4 - Testing API..."
      
            # Test if API responds with 200 OK
            if curl -sf http://localhost:5000/api/tasks; then
              echo "API is up and responding!"
              break
            fi
      
            echo "API not ready yet, waiting 5 seconds..."
            sleep 5
          done
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}

      
      - name: Stop E2E environment
        if: always()
        run: docker compose down -v
        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}


  publish:
    name: Publish Verified Image to ECR
    runs-on: ubuntu-latest
    needs: package-and-integration-tests

    steps:

      - name: Download Docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Extract and load Docker image
        run: |
          gunzip -c task-manager-image.tar.gz | docker load
          docker images | grep task-manager

      - name: Configure AWS Credentials (OIDC) - Secret      
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag Docker image
        run: docker tag task-manager:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push Docker image
        run: docker push ${{ secrets.ECR_REPOSITORY }}:latest
        
      - name: Verify pushed image
        run: docker pull ${{ secrets.ECR_REPOSITORY }}:latest

  deploy-to-eks:
    name: Deploy to EKS
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name tamar-cluster --region ap-south-1

      # - name: Deploy latest image to EKS
      #   run: |
      #     kubectl set image deployment/task-manager \
      #       task-manager-app=${{ secrets.ECR_REPOSITORY }}:latest \
      #       -n task-manager
      #     kubectl rollout status deployment/task-manager -n task-manager

      - name: Deploy latest image to EKS with Helm
        run: |
          helm upgrade --install task-manager ./task-manager \
            --namespace task-manager \
            --create-namespace \
            --set app.image=${{ secrets.ECR_REPOSITORY }}:latest \
            --wait
      
